// <auto-generated />
using EOY_API.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOY_API.Migrations
{
    [DbContext(typeof(EoyDbContext))]
    partial class EoyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOY_API.Tables.Login", b =>
                {
                    b.ToTable("Logins");
                });

            modelBuilder.Entity("EOY_API.Tables.Workplace", b =>
                {
                    b.ToTable("Workplaces");
                });
#pragma warning restore 612, 618
        }
    }
}
